extends: airbnb-base

env:
  node: true
  es6: true
  mocha: true

rules:
  no-plusplus: 0
  no-param-reassign: 0
  space-before-function-paren:
    - 2
    - always
  no-underscore-dangle: 0
  consistent-return: 0
  no-unused-expressions:
    - 2
    - allowShortCircuit: true
