extends: airbnb-base

env:
  node: true
  es6: true
  mocha: true

rules:
  no-plusplus: 0
  no-param-reassign: 0
  space-before-function-paren:
    - 2
    - always
  no-underscore-dangle: 0
  consistent-return: 0
  no-unused-expressions:
    - 2
    - allowShortCircuit: true
  no-mixed-operators: 0
  no-bitwise: 0
  one-var-declaration-per-line: 0
  one-var: 0
  no-useless-return: 0
  no-use-before-define: 1
